[workspace]
resolver = "2"

members = [
    "lib",
    "standalone",
]
default-members = ["standalone"]

[workspace.dependencies]
eframe = { version = "0.26", features = ["wgpu"] }

[profile.release]
lto = "thin"
panic = "abort"
