[workspace]
resolver = "2"

members = [
    "lib",
    "standalone",
]
default-members = ["standalone"]

[workspace.dependencies]
eframe = { version = "0.20", features = ["dark-light", "wgpu"] }

[profile.release]
lto = "thin"
panic = "abort"
