[package]
authors = ["joel nises <joel.nises@gmail.com>"]
name = "brimstone"
version = "0.1.1"
edition = "2021"

[dependencies]
eframe = { version = "0.20", features = ["dark-light", "wgpu"] }
env_logger = "0.10"
lib = { path = "../lib" }
