[package]
authors = ["joel nises <joel.nises@gmail.com>"]
name = "brimstone"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.19.0", features = ["dark-light"] }
env_logger = "0.9"
lib = { path = "../lib" }
