[package]
authors = ["joel nises <joel.nises@gmail.com>"]
name = "brimstone"
version = "0.1.2"
edition = "2021"

[dependencies]
eframe = { workspace = true }
env_logger = "0.11"
lib = { path = "../lib" }
